# Generated by Django 5.2.14 on 2026-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstylerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Price Quoted'), ('paid', 'Payment Confirmed'), ('cutting', 'Cutting Fabric'), ('sewing', 'Sewing in Progress'), ('completed', 'Ready/Shipped')], default='pending', max_length=20),
        ),
    ]
