# Generated by Django 5.2.14 on 2026-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0003_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstylerequest',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customstylerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Price Quoted'), ('paid', 'Payment Confirmed'), ('cutting', 'Cutting Fabric'), ('sewing', 'Sewing in Progress'), ('completed', 'Ready for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
