# Generated by Django 5.2.14 on 2026-07-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_customstylerequest_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customstylerequest',
            name='quote_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customstylerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Price Quoted'), ('expired', 'Quote Expired'), ('paid', 'Payment Confirmed'), ('cutting', 'Cutting Fabric'), ('sewing', 'Sewing in Progress'), ('completed', 'Ready for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FabricGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='fashion.fabricbrand')),
            ],
            options={
                'ordering': ['brand__position', 'price'],
            },
        ),
    ]
