# Generated by Django 5.2.14 on 2026-07-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0006_customstylerequest_fabric_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('swatch_image', models.ImageField(blank=True, null=True, upload_to='fabric_colors/')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='fashion.fabricgrade')),
            ],
            options={
                'ordering': ['grade', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customstylerequest',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='fashion.fabriccolor'),
        ),
    ]
