# Generated by Django 5.2.14 on 2026-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0007_fabriccolor_customstylerequest_fabric_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstylerequest',
            name='fabric_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customstylerequest',
            name='tailoring_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
