# Generated by Django 5.2.14 on 2026-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0010_alter_notification_message_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstylerequest',
            name='preferred_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
