# Generated by Django 5.2.14 on 2026-07-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_referralconfig_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_level',
            field=models.CharField(choices=[('none', 'Unverified'), ('tier1', 'Tier 1'), ('tier2', 'Tier 2')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
