# Generated by Django 5.2.14 on 2026-09-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cached_provider_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cached_provider_balance_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
