# Generated by Django 5.2.14 on 2026-09-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('marketplace', 'Marketplace'), ('fashion', 'Fashion / Custom Tailoring'), ('airtime', 'Airtime Purchase'), ('data', 'Data Bundle Purchase'), ('cable_tv', 'Cable TV Purchase'), ('electricity', 'Electricity Bill Payment'), ('wallet_funding', 'Wallet Funding')], max_length=30, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
