# Generated by Django 5.2.14 on 2026-05-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataplan',
            old_name='our_price',
            new_name='price',
        ),
    ]
