# Generated by Django 4.2.7 on 2026-05-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0002_rename_our_price_dataplan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('provider_id', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dataplan',
            options={'ordering': ['provider', 'price']},
        ),
        migrations.AddField(
            model_name='dataplan',
            name='api_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dataplan',
            name='bundle_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(choices=[('DSTV', 'DSTV'), ('GOTV', 'GOTV'), ('STARTIMES', 'STARTIMES')], max_length=10)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_id', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cable_plans', to='vtu.provider')),
            ],
            options={
                'ordering': ['provider_name', 'price'],
            },
        ),
        migrations.AddField(
            model_name='dataplan',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_plans', to='vtu.provider'),
        ),
    ]
