# Generated by Django 4.2.7 on 2026-05-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0003_add_provider_and_cableplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cableplan',
            options={'ordering': ['provider_name', 'selling_price']},
        ),
        migrations.AlterModelOptions(
            name='dataplan',
            options={'ordering': ['provider', 'selling_price']},
        ),
        migrations.RenameField(
            model_name='cableplan',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='dataplan',
            old_name='price',
            new_name='selling_price',
        ),
    ]
