# Generated by Django 4.2.7 on 2026-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0004_rename_price_to_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataplan',
            name='bundle_id',
        ),
        migrations.AlterField(
            model_name='dataplan',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel'), ('GLO', 'Glo'), ('9MOBILE', '9mobile'), ('T2MOBILE', 't2mobile')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dataplan',
            name='plan_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dataplan',
            constraint=models.UniqueConstraint(fields=('network', 'plan_id'), name='vtu_dataplan_network_plan_id_uniq'),
        ),
    ]
