# Generated by Django 4.2.7 on 2026-07-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0005_remove_dataplan_bundle_id_alter_dataplan_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableplan',
            name='plan_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='cableplan',
            constraint=models.UniqueConstraint(fields=('provider_name', 'plan_id'), name='vtu_cableplan_provider_plan_id_uniq'),
        ),
    ]
