# Generated by Django 5.2.14 on 2026-10-08 16:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0006_alter_cableplan_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableplan',
            name='api_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AIRTIME', 'Airtime'), ('ELECTRICITY', 'Electricity')], max_length=15)),
                ('provider', models.CharField(default='*', help_text='Network / disco code (e.g. MTN, IKEDC) or * for all.', max_length=20)),
                ('percent_adjust', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Negative = discount, positive = markup (percent of amount).', max_digits=6)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'provider'],
                'constraints': [models.UniqueConstraint(fields=('category', 'provider'), name='vtu_servicepricing_cat_provider_uniq')],
            },
        ),
    ]
