from django.urls import path

from .views import (
    AdminDashboardView,
    DashboardFinanceView,
    DashboardFlyerDeleteView,
    DashboardFlyerToggleView,
    DashboardFlyerUpdateView,
    DashboardFlyerUploadView,
    DashboardFlyerView,
    DashboardGalleryDeleteView,
    DashboardGalleryUpdateView,
    DashboardGalleryUploadView,
    DashboardGalleryView,
    DashboardLoginView,
    DashboardLogoutView,
    DashboardOrderListView,
    DashboardOrderUpdateView,
    DashboardPlanListView,
    DashboardPlanPriceUpdateView,
    DashboardPlanSyncView,
    DashboardPlanToggleView,
    DashboardTailoringListView,
    DashboardTailoringUpdateView,
    DashboardTransactionListView,
    DashboardUserDetailView,
    DashboardUserListView,
    DashboardUserToggleActiveView,
    DashboardWalletAdjustView,
)

urlpatterns = [
    path("", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("login/", DashboardLoginView.as_view(), name="dashboard_login"),
    path("logout/", DashboardLogoutView.as_view(), name="dashboard_logout"),
    path("plans/", DashboardPlanListView.as_view(), name="dashboard_plans"),
    path("plans/sync/", DashboardPlanSyncView.as_view(), name="dashboard_plans_sync"),
    path("plans/<int:pk>/toggle/", DashboardPlanToggleView.as_view(), name="dashboard_plan_toggle"),
    path("plans/<int:pk>/price/", DashboardPlanPriceUpdateView.as_view(), name="dashboard_plan_price"),
    path(
        "transactions/",
        DashboardTransactionListView.as_view(),
        name="dashboard_transactions",
    ),
    path(
        "tailoring/",
        DashboardTailoringListView.as_view(),
        name="dashboard_tailoring",
    ),
    path(
        "tailoring/<int:pk>/update/",
        DashboardTailoringUpdateView.as_view(),
        name="dashboard_tailoring_update",
    ),
    path("finance/", DashboardFinanceView.as_view(), name="dashboard_finance"),
    path("finance/adjust/", DashboardWalletAdjustView.as_view(), name="dashboard_wallet_adjust"),
    path("flyers/", DashboardFlyerView.as_view(), name="dashboard_flyers"),
    path("flyers/upload/", DashboardFlyerUploadView.as_view(), name="dashboard_flyer_upload"),
    path("gallery/", DashboardGalleryView.as_view(), name="dashboard_gallery"),
    path("gallery/upload/", DashboardGalleryUploadView.as_view(), name="dashboard_gallery_upload"),
    path("gallery/<int:pk>/update/", DashboardGalleryUpdateView.as_view(), name="dashboard_gallery_update"),
    path("gallery/<int:pk>/delete/", DashboardGalleryDeleteView.as_view(), name="dashboard_gallery_delete"),
    path("orders/", DashboardOrderListView.as_view(), name="dashboard_orders"),
    path("orders/<int:pk>/update/", DashboardOrderUpdateView.as_view(), name="dashboard_order_update"),
    path("flyers/<int:pk>/update/", DashboardFlyerUpdateView.as_view(), name="dashboard_flyer_update"),
    path("flyers/<int:pk>/delete/", DashboardFlyerDeleteView.as_view(), name="dashboard_flyer_delete"),
    path("flyers/<int:pk>/toggle/", DashboardFlyerToggleView.as_view(), name="dashboard_flyer_toggle"),
    path("users/", DashboardUserListView.as_view(), name="dashboard_users"),
    path("users/<int:pk>/", DashboardUserDetailView.as_view(), name="dashboard_user_detail"),
    path(
        "users/<int:pk>/toggle-active/",
        DashboardUserToggleActiveView.as_view(),
        name="dashboard_user_toggle",
    ),
]
