# Generated by Django 4.2.7 on 2026-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketinggallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinggallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketinggallery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marketinggallery',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
