# Generated by Django 4.2.7 on 2026-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketinggallery_description_marketinggallery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinggallery',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketinggallery',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
