# Generated by Django 4.2.7 on 2026-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_user', 'New User Registration'), ('new_order', 'New Market Order'), ('new_tailoring', 'New Tailoring Request'), ('new_deposit', 'New Wallet Deposit'), ('new_purchase', 'New VTU Purchase'), ('new_referral', 'New Referral')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
