# Generated by Django 5.2.14 on 2026-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_create_adminnotification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_user', 'New User Registration'), ('new_order', 'New Market Order'), ('new_tailoring', 'New Tailoring Request'), ('new_deposit', 'New Wallet Deposit'), ('new_purchase', 'New VTU Purchase'), ('new_referral', 'New Referral'), ('admin_refund', 'Admin Wallet Refund')], max_length=30),
        ),
    ]
