# Generated by Django 5.2.14 on 2026-08-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('monnify', 'Monnify'), ('nellobytes', 'Nellobytes')], max_length=20)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('outcome', models.CharField(choices=[('received', 'Received'), ('signature_rejected', 'Signature Rejected'), ('invalid_payload', 'Invalid Payload'), ('wallet_not_found', 'Wallet Not Found'), ('duplicate_ignored', 'Duplicate (Already Processed)'), ('credited', 'Credited'), ('error', 'Error')], max_length=30)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
