# Generated by Django 5.2.14 on 2026-09-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_webhooklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='outcome',
            field=models.CharField(choices=[('received', 'Received'), ('signature_rejected', 'Signature Rejected'), ('invalid_payload', 'Invalid Payload'), ('wallet_not_found', 'Wallet Not Found'), ('duplicate_ignored', 'Duplicate (Already Processed)'), ('credited', 'Credited'), ('resolved', 'Resolved'), ('error', 'Error')], max_length=30),
        ),
    ]
