# Generated by Django 5.2.14 on 2026-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('DATA', 'Data Purchase'), ('AIRTIME', 'Airtime Top-up'), ('UTILITY', 'Utility Bill'), ('DEPOSIT', 'Wallet Funding'), ('EXAMPIN', 'Exam Pin Purchase')], max_length=10),
        ),
    ]
