# Generated by Django 4.2.7 on 2026-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_add_fee_and_net_amount_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
